apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: acecicd-deploy-t
spec:
  params:
    - default: acecicd
      description: name of the ace is name
      name: isReleaseName
      type: string
    - default: ace
      description: release namespace
      name: namespace
      type: string
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: oc
      resources: {}
      script: |
        cat << EOF | oc apply -f -
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $(params.isReleaseName)
          namespace: $(params.namespace)
        spec:
          pod:
           containers:
             runtime:
               image: $(resources.inputs.image.url)
          configurations: []
          designerFlowsOperationMode: disabled
          license:
            accept: true
            license: L-APEH-BPUCJK
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          version: 11.0.0.10-r1
        EOF
