apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-aceimg
spec:
  params:
    - default: ace
      description: release namespace
      name: namespace
      type: string
    - name: image_tag
      description: image tag name
    - name: image_name
      description: image name
    - name: license
      description: license number
      default: L-APEH-BPUCJK
  resources:
    inputs:
      - name: image
        type: image
  steps:
    - image: 'quay.io/openshift/origin-cli:latest'
      name: oc
      resources: {}
      script: |
        cat << EOF > integrationserver.yaml
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: $(params.image_name)
          namespace: $(params.namespace)
        spec:
          pod:
           containers:
             runtime:
               image: $(resources.inputs.image.url)/$(params.image_name):$(params.image_tag)
          configurations: []
          designerFlowsOperationMode: disabled
          license:
            accept: true
            license: $(params.license)
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          version: 11.0.0.10-r1
        EOF
        cat integrationserver.yaml
        oc apply -f integrationserver.yaml