apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: testace
  namespace: ace
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace/acecicd:1.0
  configurations: []
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-BPUCJK
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0.10-r1